name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "main"
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  EZIP_VERSION: 0.0.5

jobs:
  repackage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin

      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      - run: which deno && deno --version

      - name: pkg_8zip
        run: bash ./scripts/pkg_8zip.bash

      - name: pkg_deno
        run: bash ./scripts/pkg_deno.bash

      - name: pkg_eza
        run: bash ./scripts/pkg_eza.bash

      - name: pkg_flatdir
        run: bash ./scripts/pkg_flatdir.bash

      - name: pkg_fnm
        run: bash ./scripts/pkg_fnm.bash

      - name: pkg_gh
        run: bash ./scripts/pkg_gh.bash

      - name: pkg_go
        run: bash ./scripts/pkg_go.bash

      - name: pkg_http-server-rs
        run: bash ./scripts/pkg_http-server-rs.bash

      - name: pkg_hyperfine
        run: bash ./scripts/pkg_hyperfine.bash

      - name: pkg_just
        run: bash ./scripts/pkg_just.bash

      - name: pkg_node
        run: bash ./scripts/pkg_node.bash

      - name: pkg_oha
        run: bash ./scripts/pkg_oha.bash

      - name: pkg_python
        run: bash ./scripts/pkg_python.bash

      - name: pkg_rrm
        run: bash ./scripts/pkg_rrm.bash

      - name: pkg_terraform
        run: bash ./scripts/pkg_terraform.bash

      - name: pkg_vultr-cli
        run: bash ./scripts/pkg_vultr-cli.bash

      - name: pkg_zenith
        run: bash ./scripts/pkg_zenith.bash

      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
 
  # Custom Builds
  pkg_eza_build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-macos-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: bash ./scripts/pkg_eza_build_macos.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  publish-github-release:
    name: "🔄 Publish Github Release"
    runs-on: ubuntu-24.04
    needs:
      - repackage
      - pkg_eza_build_macos
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with: 
          path: binaries
          merge-multiple: true
      - run: cd binaries && for item in *; do echo "$item"; [ -d "$item" ] && for subitem in "$item"/*; do [ -e "$subitem" ] && echo "  $subitem"; done; done || true
      # Install Deno
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      # Generate release
      - run: deno install
      - run: deno -A ./site/cmd/generate-release.mts --run

  publish-pages:
    name: "📃 Publish Pages"
    runs-on: ubuntu-24.04
    needs:
      - publish-github-release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v5
      # Install Deno
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      # Generate pages
      - run: deno install
      - run: deno -A ./site/cmd/generate-package-index.mts --run
      - run: deno -A ./site/cmd/copy-files.mts --run
      - run: deno -A ./site/cmd/build-shell-scripts.mts --run
      - run: deno -A ./site/cmd/build-page.mts --run
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'dist' }
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release-latest:
    name: "📃 Republish Latest"
    runs-on: ubuntu-24.04
    needs:
      - publish-github-release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v5
      # Install Deno
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      # Generate pages
      - run: deno install
      - run: deno -A ./site/cmd/republish-latest.mts --run
  

